### ISSUE TITLE
BaseSocket always sends data as long as the longest previous data.

### ISSUE THREAD

**Issue by camerongivler** [Aqueti/tools#4]
BaseSocket seems to have an issue where if I send "hello" then "hi", what actually comes through ends up being "hillo" the second time.  The following is the code used:

`    std::ostringstream stream;`
`    val.writeToStream(stream, false);`
`    client.sendData((void*) stream.str().c_str(), stream.str().length());`
`    std::cout << stream.str().c_str() << " " << stream.str().length() << std::end;`

The output on the sending side is:
hello 5
hi 2

and in SampleServer:
hello
hillo

**Comment by camerongivler** [comment]
I found the issue with my code... The length() function does not include the null terminator, so adding 1 to length() fixes the issue.  I am puzzled why this is the response caused by length being off by one, though.  I would expect that a null terminator would not be necessary.

**Comment by sfeller** [comment]
Cameron, if this is complete, let's close it out.
