### ISSUE TITLE
HandleMessageCallback should indicate sender id

### ISSUE THREAD

**Issue by camerongivler** [Aqueti/tools#5]
HandleMessageCallback should indicate the "index" of the sender in BaseServer so that a reply can be sent, or a specific message can be tagged as a particular user.  It shouldn't be the client's job to identify themselves.

**Comment by sfeller** [comment]
I"ve modified the code so that that callback includes the index of sender in branch b860ba9dc08f2e7361e66c031e200dc81d0475f7. Closing
